version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.0.0

jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run: ng build
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-region: AWS_REGION_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
          from: dist/client-front-end
          overwrite: true
          to: 's3://reportyfrontend'

workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master