version: 2.1
jobs:
  build:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - checkout
      - run: ng build
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
          aws-region: AWS_REGION_BLUE
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY_BLUE
          from: dist/client-front-end
          overwrite: true
          to: 's3://reportyfrontend'
orbs:
  aws-cli: circleci/aws-cli@0.1

# workflows:
#   version: 2
#   build-master:
#     jobs:
#       - build:
#           filters:
#             branches:
#               only: master
#       - publish-latest:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master