# version: 2.1

# orbs:
#   aws-cli: circleci/aws-cli@0.1

# jobs:
#   build:
#     docker:
#       - image: 'cimg/python:3.6'
#     steps:
#       - checkout
#       - run: ng build
#       - aws-s3/sync:
#           arguments: |
#             --acl public-read \
#             --cache-control "max-age=86400"
#           aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
#           aws-region: AWS_REGION_BLUE
#           aws-secret-access-key: A WS_SECRET_ACCESS_KEY_BLUE
#           from: dist/client-front-end
#           overwrite: true
#           to: 's3://reportyfrontend'

version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.22

jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
          - checkout
          - run: ng build
          - aws-s3/sync:
              arguments: |
                --acl public-read \
                --cache-control "max-age=86400"
              aws-access-key-id: AWS_ACCESS_KEY_ID_BLUE
              aws-region: AWS_REGION_BLUE
              aws-secret-access-key: A WS_SECRET_ACCESS_KEY_BLUE
              from: dist/client-front-end
              overwrite: true
              to: 's3://reportyfrontend'

workflows:
  version: 2
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws
# workflows:
#   version: 2
#   build:
#     jobs:
#       - build:
#           filters:
#             branches:
#               only: master
